use 24-bit color escapes (ISO-8613-6) unless --enable-tf-compat
xterm has supported approximation to palette colors for these for a
while now, and in addition now support directColor to render the correct
color directly.

we add --enable-tf-compat configure option and keep 256color.c around
for that; tf 5.0b8 understands xterm 256 colors, but not 24-bit color.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,6 +7,22 @@ echo '#ifndef CONFIG_H' >&3
 echo '#define CONFIG_H' >&3
 CC=${CC-cc}
 
+color=color.c
+while [ -n "$1" ]; do
+    case "$1" in
+        --enable-tf-compat)
+            echo "compat mode: 24-bit colors disabled"
+            color=256color.c
+            ;;
+        *)
+            echo "invalid option $1" >&2
+            exit 1
+            ;;
+    esac
+    shift
+done
+echo "SRCS+=    $color" >&4
+
 printf "checking for libtls: "
 if ${CC} -o config/out config/libtls_test.c -ltls 2>/dev/null; then
     echo '#define HAVE_LIBTLS' >&3
